Query and update animals
braincee/Vet-Clinic-Database pull request #2
Opened 2022-07-06 19:16 UTC by braincee

- I added a column species of type string to your animal's table and Modified my `schema.sql` file using ALTER command.
- I inserted the following data into the `data.sql` file:
    - Animal: His name is Charmander. He was born on Feb 8th, 2020, and currently weighs -11kg. He is not neutered and he has 
       never tried to escape.
   - Animal: Her name is Plantmon. She was born on Nov 15th, 2021, and currently weighs -5.7kg. She is neutered and she has 
      tried to escape 2 times.
   - Animal: His name is Squirtle. He was born on Apr 2nd, 1993, and currently weighs -12.13kg. He was not neutered and he 
     has tried to escape 3 times.
   - Animal: His name is Angemon. He was born on Jun 12th, 2005, and currently weighs -45kg. He is neutered and he has tried 
     to escape once.
   - Animal: His name is Boarmon. He was born on Jun 7th, 2005, and currently weighs 20.4kg. He is neutered and he has tried 
      to escape 7 times.
  -  Animal: Her name is Blossom. She was born on Oct 13th, 1998, and currently weighs 17kg. She is neutered and she has tried 
     to escape 3 times.
  -  Animal: His name is Ditto. He was born on May 14th, 2022, and currently weighs 22kg. He is neutered and he has tried to 
     escape 4 times.

![Screenshot (135)](https://user-images.githubusercontent.com/78104544/177619522-d0f972cf-2b70-4f02-adfb-3f2767e592d4.png)

- I added a transaction update for the animals' table by setting the species to unspecified and rollback.

![Screenshot (136)](https://user-images.githubusercontent.com/78104544/177620368-b0eecbd2-c7bc-45de-9f20-25daa6217249.png)

- I updated the animals' table by setting the species column to digimon for all animals that have a name ending in mon.
- I updated the animals' table by setting the species column to pokemon for all animals that don't have species already set.
 - I committed the transaction and verified the changes made persisted after the commit.
 
![Screenshot (137)](https://user-images.githubusercontent.com/78104544/177621368-fbb341e2-8566-48c7-aa4c-416602956554.png)

- In a delete transaction, all the animals in the table were deleted. Then I rolled back the transaction. After the rollback, I verified if all the transactions exists.

![Screenshot (138)](https://user-images.githubusercontent.com/78104544/177622339-2cbaf1ad-4240-4757-9042-85927688c56e.png)

- In the next transaction I deleted all animals born on January 1st, 2022, then created a savepoint for the transaction.

![Screenshot (139)](https://user-images.githubusercontent.com/78104544/177623024-5f77013c-78da-4bce-b147-a7f9c1a73273.png)

- I updated the animals' weight to be their weight multiplied by -1 then rolled back the savepoint. 

![Screenshot (140)](https://user-images.githubusercontent.com/78104544/177623723-2614a3a1-16ca-42ac-ac69-68b5fd4df5ac.png)

- I updated all animals' weights that are negative to be their weight multiplied by -1 and then committed the transaction.

![Screenshot (141)](https://user-images.githubusercontent.com/78104544/177624479-820ebec0-abd0-489e-8f0e-8d0b18f16bb8.png)

- I wrote queries to answer the following questions
  - How many animals are there?
  - How many animals have never tried to escape?
  - What is the average weight of animals?
  - Who escapes the most, neutered or not neutered animals?
  
 
![Screenshot (143)](https://user-images.githubusercontent.com/78104544/177625467-58aee933-4d41-47aa-a769-bb97181edecc.png)

   - What is the minimum and maximum weight of each type of animal?
   - What is the average number of escape attempts per animal type of those born between 1990 and 2000?

![Screenshot (144)](https://user-images.githubusercontent.com/78104544/177625790-94bf1da6-5ef5-446d-9029-29e95c6dd491.png)

2022-07-06 19:28 UTC, DeliceLydia requested changes
## Hi @braincee, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._



### Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-06 19:28 UTC, DeliceLydia commented on queries.sql
> +UPDATE animals SET species = 'unspecified';
- [ ] I suggest that you verify that change was made and if it is persisting:
```
` SELECT species from animals; -- verify that change was made
   ROLLBACK;

   SELECT species from animals; -- verify that change was undone
`
```

2022-07-06 19:28 UTC, DeliceLydia commented on queries.sql
> +COMMIT;
- [ ] Same here before committing please verify:
```
 SELECT species from animals; -- verify that change was made
   ROLLBACK;

   SELECT species from animals; -- verify that change was undone
```

2022-07-06 20:32 UTC, EricMbouwe approved these changes
Hi @braincee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good PR
- Linters ok
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 09:54 UTC, merged

2022-11-12 11:23 UTC, braincee commented
Thanks very much, @EricMbouwe  @DeliceLydia 

![thank-you](https://user-images.githubusercontent.com/78104544/201471694-37385db8-f58e-4944-9291-83c24bfe33a9.gif)